- name: ping, install and run the nginx
  hosts: web
  become: yes
  tasks:
  - name: pinging the server
      ansible.builtin.ping:
  - name: install nginx
      ansible.builtin.dnf:
      name: nginx
      state: latest
  - name: start the service
      ansible.builtin.service:
      state: started
      enabled: yes
